services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=fuel_table
      - PGUSER=postgres
      - PGPASSWORD=vik8989
      - WEBSOCKET_URL=ws://209.38.217.58:8093
      - PORT=4000
      - SUPABASE_URL=https://hziksqggnmjftimwgyyk.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6aWtzcWdnbm1qZnRpbXdneXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NDc5NDQsImV4cCI6MjA4NTQyMzk0NH0.4_n8TXZ1lKYer2srmtexe1En1KfEnehXmykvsjqGVBY
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fuel_table
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vik8989
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
