services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PGHOST=postgres
      - PGPORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=fuel_table
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vik8989
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
